import type { DashboardLockbox, DashboardStats } from "@/components/dashboard/types";

export const dashboardStats: DashboardStats = {
  totalRevenueLabel: "$5,240",
  activeLinksLabel: "12",
  totalTipsLabel: "$480",
};

export const dashboardLockboxes: DashboardLockbox[] = [
  {
    id: "1",
    title: "Website_Assets_v2.zip",
    fileSize: "24.5 MB",
    priceLabel: "$150.00",
    priceCents: 15000,
    createdLabel: "Oct 24, 2024",
    createdAt: "2024-10-24T00:00:00.000Z",
    status: "paid",
    icon: "lock",
    previewText: "Full website asset package",
    previewUrl: "https://example.com/preview1.png",
    secureLink: "https://example.com/download/1",
    platformFeePercent: 8,
    requiresPassword: false,
    isListed: false,
  },
  {
    id: "2",
    title: "Brand_Guidelines.pdf",
    fileSize: "5.2 MB",
    priceLabel: "$75.00",
    priceCents: 7500,
    createdLabel: "Oct 23, 2024",
    createdAt: "2024-10-23T00:00:00.000Z",
    status: "pending",
    icon: "image",
    previewText: "Brand usage guidelines",
    previewUrl: "https://example.com/preview2.png",
    secureLink: "https://example.com/download/2",
    platformFeePercent: 7,
    requiresPassword: false,
    isListed: false,
  },
  {
    id: "3",
    title: "Source_Code_Final.zip",
    fileSize: "128 MB",
    priceLabel: "$1,200.00",
    priceCents: 120000,
    createdLabel: "Oct 20, 2024",
    createdAt: "2024-10-20T00:00:00.000Z",
    status: "paid",
    icon: "bar_chart",
    previewText: "Production-ready source code",
    previewUrl: "https://example.com/preview3.png",
    secureLink: "https://example.com/download/3",
    platformFeePercent: 10,
    requiresPassword: false,
    isListed: false,
  },
];
